---
# Ruta de destino en los servidores Windows
windows_dest_path: "C:\\sys\\"

# Archivos a copiar desde la fuente
windows_files_to_copy:
  - "ncpa.exe"
  - "Instalar_Nagios_KIO.BAT"
  - "Instalar_Nagios_TRIARA.BAT"
