---
# run_software_installation.yml

- name: "SOFTWARE INSTALLATION: Ejecutar en servidores Linux"
  hosts: LINUX
  gather_facts: yes
  become: yes
  ignore_unreachable: true   # Continuar con los siguientes hosts aunque este no responda
  any_errors_fatal: false
  max_fail_percentage: 100
  roles:
    - software_installer

- name: "SOFTWARE INSTALLATION: Ejecutar en servidores Windows (PROD)"
  hosts: PROD
  gather_facts: yes
  become: no
  ignore_unreachable: true
  any_errors_fatal: false
  max_fail_percentage: 100
  roles:
    - software_installer

- name: "SOFTWARE INSTALLATION: Ejecutar en servidores Windows (DRP)"
  hosts: DRP
  gather_facts: yes
  become: no
  ignore_unreachable: true
  any_errors_fatal: false
  max_fail_percentage: 100
  roles:
    - software_installer

- name: "SOFTWARE INSTALLATION: Generar reportes consolidados (Control Node)"
  hosts: invd-ts-ansible
  gather_facts: yes
  vars:
    report_ts: "{{ ansible_date_time.iso8601_basic_short }}"
    report_dir: "/reportes_ansible/software_installation/{{ report_ts }}"
  tasks:
    - name: Crear directorio del reporte en el nodo de control
      ansible.builtin.file:
        path: "{{ report_dir }}"
        state: directory
        mode: '0755'

    - name: Inicializar listas consolidadas para resultados por OS
      ansible.builtin.set_fact:
        installation_results_linux: []
        installation_results_windows: []

    - name: Consolidar resultados de LINUX (incluyendo fallos)
      ansible.builtin.set_fact:
        installation_results_linux: "{{ installation_results_linux + [ host_result ] }}"
      vars:
        host_result: >-
          {{
            hostvars[item].software_installation_result
            | default({
                'host': item,
                'os_family': 'Linux',
                'overall_status': 'unreachable',
                'message': 'Host no alcanzable o error antes de la instalacion'
              })
          }}
      loop: "{{ groups['LINUX'] | default([]) }}"

    - name: Consolidar resultados de WINDOWS (PROD + DRP)
      ansible.builtin.set_fact:
        installation_results_windows: "{{ installation_results_windows + [ host_result ] }}"
      vars:
        windows_hosts: "{{ groups['PROD'] | default([]) + groups['DRP'] | default([]) }}"
        host_result: >-
          {{
            hostvars[item].software_installation_result
            | default({
                'host': item,
                'os_family': 'Windows',
                'overall_status': 'unreachable',
                'message': 'Host no alcanzable o error antes de la instalacion'
              })
          }}
      loop: "{{ windows_hosts }}"

    - name: Renderizar reportes finales usando templates del rol
      ansible.builtin.include_role:
        name: software_installer
        tasks_from: render_reports.yml